### PR TITLE
 Remove hardcoded pk's from fixtures

### PR DESCRIPTION
**Pull request by jloeser**
In order to do this, we need some changes for the type constants.

### CODE REVIEW

**Comment by jloeser** [comment]
Local tests run fine, here its failing. I need to understand how these automatic tests are working her when creating PR.

**Comment by watologo1** [comment]
I guess you mean:
.github/workflows/django.yml
?

If you would have keep the request, there should be something here pointing to a error message to look at?

**Comment by watologo1** [comment]
Reopening to see CI error.

**Comment by jloeser** [comment]
> I guess you mean:
> .github/workflows/django.yml
> ?

Exactly, this is the missing part I was looking for. Never worked with that :)

> 
> If you would have keep the request, there should be something here pointing to a error message to look at?

That's true, I closed it because I was afraid of people may just merge it even if there are test errors because this is/was not really reliable for the last changes.

However, looks like there are no fixtures installed at all in these automatic tests?

**Comment by watologo1** [comment]
> However, looks like there are no fixtures installed at all in these automatic tests?

Looks like a call to:
bin/install_all_fixtures.sh

is missing after changing into orthos2 dir and before running the test?

You simply may want to update the request by updating your branch this request is against.

**Comment by jloeser** [comment]
Why is there no test running after last commit?

**Comment by watologo1** [comment]
Strange..., there should definitely be some failure here....

On the main orthos2 "action" tab I found:
 Check failure on line 37 in .github/workflows/django.yml


GitHub Actions
/ Django CI

Invalid workflow file
The workflow is not valid. .github/workflows/django.yml (Line: 37, Col: 7): 'run' is already defined

If you fix this, things should move on again...?

**Comment by watologo1** [comment]
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

**Comment by watologo1** [comment]
Krass, ich kann direkt im review Prozess, im browser Deinen commit veraendern und sogar in Deine branch committen.

CI laeuft wieder.. ;)

**Comment by watologo1** [comment]
Ich kenn mich da aber zu wenig aus. Da soll Christian mal drueber schauen....

**Comment by jloeser** [comment]
> Krass, ich kann direkt im review Prozess, im browser Deinen commit veraendern und sogar in Deine branch committen.
> 

wtf!

**Pull request merged**
