### PR TITLE
Cvoegl test

### PR DESCRIPTION
**Pull request by loreson**

### CODE REVIEW

**Comment by SchoolGuy** [comment]
What does this PR do? What is it for? Why are there so many conflicts?

**Comment by watologo1** [comment]
> What does this PR do? What is it for? Why are there so many conflicts?

I guess this comes from the huge shifting around of files.
Mostly for:
- Split out wsgi parts
- Split out static and template html files

And a lot module namespace adjusting, due to create proper orthos2 namespace
E.g. wsgi code used:
     import data
This worked because the wsgi server/plugin was started inside the orthos2 site-packages code as declared in the wsgi.ini file:
     chdir           = /usr/lib/python3.6/site-packages/orthos2

And in parallel there has been all the packaging work and additional the Django update from Jan got integrated, as I already run into package dependency issues when working on packaging.

I agree, that this is a huge mess. But we have to go through this once.

@jloeser We might want to have a chat before merging this. Reviewing takes hours. I would explain the main changes why files have been moved and modules namespace got adjusted.

If we all agree that this makes sense, then let's give it a push and fix up "introduced" side-effects step by step on top of it.
We then should not diverge that much anymore and push things more regularly.
In this case this was not possible, as we needed a working build/rpm solution with a lot changes...

**Comment by watologo1** [comment]
> E.g. wsgi code used:
> import data

It has to be:
import orthos2.data
Like this the code can be anywhere and the proper orthos2 modules are found here:
/usr/lib/python-*/site-packages/orthos2/...

**Comment by SchoolGuy** [comment]
@loreson Why are you fixing all this manually. Just take the changes you need to pick and apply them onto master. Creating these commits is bad in my eyes for two reasons:

1. We have commits breaking stuff which has worked
2. We have commits fixing stuff which was broken by your work.

Thus I would love if you could take your work and apply it on top of `master`. I think this should also be a lot faster then to fix all the merge conflicts & bugs manually etc. etc.

**Comment by jloeser** [comment]
What are we try to achieve here exactly and what's the benefit? From my understanding this is all about having a Orthos2 Python module in hand responsible for installation files into filesystem whereas the spec file only cares about the minor stuff around like the systemd unit files, etc. - is this correct? Is this the correct way to go for actually Django applications? \

This whole topic beats me a bit. However you guys should think about rebasing oon master from time to time instead of mashing up feature branch with merges.

**Comment by loreson** [comment]
@jloeser I agree, this got a bit large. I'll try to keep features better separated in the future.
I think you understood this correctly, I'm not sure if thats the django way to go, but we need an rpm for internal reasons and this works. 
The CI failure seems to be a bug in the CI pipline, as this code works on tumbleweed.

**Pull request merged**
