### PR TITLE
Cobbler: Replace SSH with XML-RPC API calls

### LINKED ISSUE #255: Switch Cobbler utils to XML-RPC API
Current Orthos uses SSH to log into the Cobbler server and execute Cobbler CLI commands. This is very bad as error handling is harder and we are less flexible in terms of reusability of the code that manages Cobbler. Lastly, the performance should increase with the XML-RPC API.

### PR DESCRIPTION
**Pull request by SchoolGuy**
Fixes #255 

This PR aims to switch from SSH-based command execution for Cobbler to a more robust XML-RPC command execution.

Due to dependency updates in openSUSE Tumbleweed, this PR also adds support for Django 5.0 and later.

Advantages:

- Easier session cleanup
- Better testing
- Better error handling
- Easier to understand
- Easier setup (no messing with SSH keys)
- Hopefully: Better performance since no SSH sessions need to be opened

Open points:

- [x] How to securely store the password? - #262
- [x] Wait for https://github.com/cobbler/cobbler/issues/3799 so we can correctly handle the kernel options of unsaved items.
- [x] Fix the unit tests

### CODE REVIEW

**Comment by SchoolGuy** [comment]
During fixing the unit tests an issue appeared. If the Cobbler Daemon is started in the foreground it listens on localhost to port 25151 for XML-RPC requests. This however doesn't include the HTTP API and furthermore ignores requests that are not done via localhost. Since in the test container, no nginx/apache is started the requests from Orthos are not being answered.

**Comment by SchoolGuy** [comment]
Now the errors are coming from Django 5 in openSUSE Tumbleweed.

**Comment by SchoolGuy** [comment]
The PR is now in a reviewable state. All above mentioned issues have been taken care of.

**Review by ByteOtter — APPROVED** [review]
lgtm 👍🏼

**Comment by SchoolGuy** [comment]
Since @ByteOtter will be part of the Orthos 2 reviewer team in the future I will count his review as a full one. His application to join the GitHub Team is already in progress.

**Pull request merged**
