### PR TITLE
Handle empty list of valid domain endings

### PR DESCRIPTION
**Pull request by jloeser**
Accept all domains by default if no valid domain endings are given in
the server configuration.

### CODE REVIEW

**Review by m-rey — COMMENTED** [review]
code looks good to me

**Comment by jloeser** [comment]
Any comments/update here? If not can you guys merge, please?

**Review by SchoolGuy — APPROVED** [review]
LGTM. Same as the other one, was being thrown overboard on a notification storm I had.

**Comment by SchoolGuy** [comment]
@watologo1 Please merge if this is okay for you!

**Comment by watologo1** [comment]
I cherry-picked this and will open a pull request against trenn_test.
This one will be the new master as soon as it's stable.
We will then do a release and work on master branch, like people would expect it to be...
Sorry for any inconvenience due to master being stale, this will change soon.

**Pull request closed without merging**
