### PR TITLE
Support to run standalone development instance

### PR DESCRIPTION
**Pull request by MingZhai**
Current code expects environment as it would be when installed as
package('/var/lib/orthos2') and depends by default on files outside
of repository(log file, database). For development mode everything
should stay inside this git repository, to simplify installation.

Simply follow the 'docs/adminguide/setup_devel.rst' manual on how to
use it.

### CODE REVIEW

**Comment by jloeser** [comment]
Any comments/update here? If not can you guys merge, please?

**Review by SchoolGuy — APPROVED** [review]
Sorry. This was killed by a notification storm I had. Yes this is LGTM in my eyes.

**Comment by SchoolGuy** [comment]
@watologo1 If you find it appropriate please merge it. I am not working actively with Orthos 2.

**Comment by watologo1** [comment]
Finally we have moved everything to master for a while now.
If you still need this patch, please rebase.

**Comment by MingZhai** [comment]
> Finally we have moved everything to master for a while now.
> If you still need this patch, please rebase.

I updated/synchronized my enableDevMode branch from openSUSE:orthos.  I will keep this branch in my forked repository. thx.

**Pull request closed without merging**
